# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
    pod 'PodA', :subspecs => ['Core'], :path => '../PodA'
    pod 'PodB', :subspecs => ['Core'], :path => '../PodB'
end

target 'Share' do
    inherit! :none

    pod 'PodA', :subspecs => ['Extra'], :path => '../PodA'
    pod 'PodB', :subspecs => ['Extra'], :path => '../PodB'
end
